### ISSUE TITLE
Append to CommandBar.PrimaryCommands

### ISSUE THREAD

**Issue by allan2** [microsoft/windows-app-rs#15]
Is there a way to add items to the PrimaryCommands collection?

```rust
let cmd_bar = CommandBar::new()?;
let add_btn = AppBarButton::new()?;
let add_icon = SymbolIcon::new()?;
add_icon.SetSymbol(Symbol::Add)?;
add_btn.SetLabel("Add Task")?;
add_btn.SetIcon(add_icon)?;
cmd_bar.PrimaryCommands()?.Add(add_btn)?; // something like this
```

[1] [WinUI 3 docs on CommandBar](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.commandbar?view=winui-3.0)
[2] [WinUI 3 docs on PrimaryCommands](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.commandbar.primarycommands?view=winui-3.0#Microsoft_UI_Xaml_Controls_CommandBar_PrimaryCommands)

**Comment by kennykerr** [comment]
I'm sorry I don't have any experience with the WinUI APIs. You may want to ask API-specific questions on the WinUI repo: 

https://github.com/microsoft/microsoft-ui-xaml

**Comment by riverar** [comment]
Hey @allan2, I believe there are still a few quirks to iron out with dependency tracking (@kennykerr?).

If you add `Windows::Foundation::Collections::IObservableVector` to your `build!` macro explicitly, `Append` and other methods should be visible.

![image](https://user-images.githubusercontent.com/475132/124534901-0ca1e180-ddca-11eb-9fb7-daf656fd416c.png)

**Comment by kennykerr** [comment]
Yes, dependencies that involve generic interfaces, such as `IObservableVector<T>`, are not correctly tracked. Here's the issue for that: https://github.com/microsoft/windows-rs/issues/772

**Comment by allan2** [comment]
Awesome. That worked. Thanks @riverar @kennykerr!
