### ISSUE TITLE
STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by drewcrawford** [microsoft/windows-app-rs#23]
## Problem
The reproducer [here](https://github.com/drewcrawford/access-violation) performs an access violation, which I don't think ought to be possible in safe rust.

I suspect this is really a bug in windows-rs, related to uninitialization of the field `App.Window`, but since it involves this crate I'm tentatively putting it here, feel free to move.

## Steps to reproduce

1. `cargo run`

```
>cargo run
   Compiling simple_window v0.0.0 (C:\Users\drew\CLionProjects\access-violation)
    Finished dev [unoptimized + debuginfo] target(s) in 2.41s
     Running `target\debug\simple_window.exe`
error: process didn't exit successfully: `target\debug\simple_window.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

## Notes
* Output from `cargo version`:
  ` cargo 1.53.0 (4369396ce 2021-04-27)`
* Output from `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\drew\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)
```
* Output from `rustup --version`:
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0 (53cb7b09b 2021-06-17)`
```
* Output from `cmd /c ver`:

```
Microsoft Windows [Version 10.0.19043.1055]
```

**Comment by riverar** [comment]
Hey @drewcrawford! The `Window` is getting disposed. Stash the main window instance in the App structure (that's why that field is there). There's a sample here as well: https://github.com/microsoft/windows-samples-rs/blob/master/windows_app_sdk/simple_window/src/main.rs#L59

**Comment by drewcrawford** [comment]
I appreciate that workaround!  However, this is a soundness issue. STATUS_ACCESS_VIOLATION is a memory violation, which isn't expected in safe rust.  Assuming that's not a winui bug, it implies the rust projection ought to be marked `unsafe`.

For the rust side, see https://github.com/microsoft/windows-rs/blob/bf9da585055128b423473aae5e36df7bd5c91019/.github/safety.md#safety

For the winui side, it seems a bit awkward that an API like `Window::new` would be unsafe.  Rust developers have a tendency to make wrappers for these cases, I'm a little uncertain whether that's in-scope here or more of a third-party crate.

**Comment by kennykerr** [comment]
In general, the xaml api will call C's abort function when used incorrectly in order to produce a Watson dump. This is considered safe on Windows because the process is immediately suspended and then terminated to prevent curruption.

**Comment by drewcrawford** [comment]
Wouldn’t abort [raise SIGABRT](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/abort?view=msvc-160)? Here we have access_violation, which I assume is some different signal (SIGSEGV presumably)

It’s a bit surprising that C abort could present like this crash, although maybe that is just how windows implements it?

**Comment by kennykerr** [comment]
I'm not a debugging expert but I think it depends on whether the abort was explicit or implicit. On Windows at least, you can abort explicitly via terminate/abort functions or implicitly by dereferencing a null pointer. The result is the same - suspension, dump, termination. This is a long-standing practice in COM code particularly and provides reliable crash dump information.
