### ISSUE TITLE
windows_app_sdk `STATUS_STACK_BUFFER_OVERRUN`

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-app-rs#24]
## Problem
```
`target\debug\skeleton.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
`target\debug\simple_window.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

## Steps to reproduce
Build and launch on Win Server 2019 (with last updates)

## Screenshots
![изображение](https://user-images.githubusercontent.com/25817412/126913875-9da10fca-f564-49d8-9d51-3e939790ce02.png)
![изображение](https://user-images.githubusercontent.com/25817412/126913959-aade7406-f828-40f7-ab58-ed2f69e7ed90.png)
![изображение](https://user-images.githubusercontent.com/25817412/126916295-284e14cf-9960-429a-8010-d45af8c508ef.png)

## Notes
* Output from `cargo version`: 1.55.0-nightly (cebef2951 2021-07-22)
* Output from `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  D:\SW\Dev\Rust\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.56.0-nightly (d9aa28767 2021-07-24)
```
* Output from `rustup --version`: rustup 1.24.3 (ce5817a94 2021-05-31)
* Output from `cmd /c ver`: Microsoft Windows [Version 10.0.17763.2061]

**Comment by riverar** [comment]
Hey @Zymlex:

Are you running your app elevated/as a built-in Administator? If so, that's not supported and would throw the following error behind the scenes:
```
ModLoad: 00007ff8`f7aa0000 00007ff8`f7ace000   C:\Windows\System32\IMM32.DLL
D:\a\1\s\dev\ProjectReunion_BootstrapDLL\MddBootstrap.cpp(36)\Microsoft.ProjectReunion.Bootstrap.dll!00007FF8E7C11223: (caller: 00007FF7F7891753) FailFast(1) tid(16d0) 80070032 The request is not supported.
    Msg:[DynamicDependencies Bootstrap doesn't support elevation. See Issue #567 https://github.com/microsoft/ProjectReunion/issues/567] 
(9fc.16d0): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
```

**Comment by Zymlex** [comment]
>Are you running your app elevated/as a built-in Administator?

Yes, I use builtin admin (and disabled UAC through GP).

**Comment by Zymlex** [comment]
It looks like the installation failed: https://github.com/microsoft/WindowsAppSDK/releases/tag/v0.8-preview

**Comment by riverar** [comment]
@Zymlex I filed a bug on that; requires sideloading of packages. https://github.com/microsoft/WindowsAppSDK/issues/1119

But then you'll run into my next bug as well. https://github.com/microsoft/WindowsAppSDK/issues/1121
