### ISSUE TITLE
the second sample in your readme produces an error

### ISSUE THREAD

**Issue by clovett** [microsoft/windows-app-rs#31]
## Problem

Running this sample:
```rust
fn main() -> ::windows::core::Result<()> {
    println!("starting app");
    bootstrap::initialize()
        .and_then(|_| {
            println!(
                "Remaining charge: {}%",
                PowerManager::RemainingChargePercent()?
            );
            Ok(())
        })
        .and_then(|_| bootstrap::uninitialize())
}
```
produces this error:

Error: Error { code: 0x80070491, message: There was no match for the specified key in the index.
, win32_error: 1169 }

## Steps to reproduce

Follow the readme.

## Notes
* Output from `cargo version`:  
  cargo 1.57.0 (b2e52d7ca 2021-10-21)
* Output from `rustup show`: 
  Default host: x86_64-pc-windows-msvc
  rustup home:  C:\Users\lovet\.rustup
  stable-x86_64-pc-windows-msvc (default)
  rustc 1.57.0 (f1edd0429 2021-11-29)

* Output from `rustup --version`:  
  rustup 1.24.3 (ce5817a94 2021-05-31)
* Output from `cmd /c ver`: 
  Microsoft Windows [Version 10.0.22000.376]

**Comment by riverar** [comment]
@clovett Hey Chris, sorry about that. You'll need to also install the Windows App SDK Runtime (1.0). 

1. Download https://download.microsoft.com/download/7/4/1/7411b780-569f-4d46-b332-5a5619127239/Microsoft.WindowsAppRuntime.Redist.1.0.0.zip.
2. Execute `WindowsAppSDK-Installer-{arch}\WindowsAppRuntimeInstall.exe`.
3. Try the sample again.

**Comment by riverar** [comment]
@lovettchris Agreed.

I've had great success just using the C/C++ Windows debugger. Here's a sample launch configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/target/debug/sample.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal"
        }
    ]
}
```

**Comment by lovettchris** [comment]
Brilliant!  Please add that to your readme also!

**Comment by erichfrazer** [comment]
oy, where do I put that above debug configuration? What file? (the answer will help others)

**Comment by FreddyD-GH** [comment]
@erichfrazer the configuration above goes in the `launch.json` file for VS Code. See https://code.visualstudio.com/Docs/editor/debugging#_launch-configurations

**Comment by riverar** [comment]
Thanks, added a note to the README about the runtime. I don't think general Rust (on Windows) debug advice fits in the repository's README but I'll do some scouting and see if there's a better home for that. (Perhaps in the future we could open up the wiki area and link to that.)

**Comment by daniellivingston** [comment]
Just a quick note -- following the instructions didn't *totally* work for me (that is to say, installing the SDK with `WindowsAppSDK-Installer-x64/WindowsAppRuntimeInstall.exe`). I continued to get errors like:

```text
Error: Error { code: 0x80070491, message: There was no match for the specified key in the index.
 }
```

However, running each of the MSIX distributables in `Microsoft.WindowsAppRuntime.Redist.1.0.0/MSIX/win10-x64` fixed the issue.

**Comment by FreddyD-GH** [comment]
@daniellivingston did you run `WindowsAppRuntimeInstall.exe` as an administrator?  My experience has been that it needs to be run as an administrator, or else it will fail to install all the packages.  Not sure if that is by design or not, but if the elevation requirement is intentional (I'm guessing that it is), perhaps it would be beneficial to add that to the README.
