### ISSUE TITLE
Can't use `implement` macro for `Application`

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/windows-app-rs#38]
## Problem
I am trying to use the `implement` macro to implement a subclass of `Microsoft::UI::Xaml::Application`. It produces a build error

```
error[E0599]: no function or associated item named `new` found for struct `windows_app::Microsoft::UI::Xaml::IApplication_Vtbl` in the current scope
error[E0599]: no function or associated item named `matches` found for struct `windows_app::Microsoft::UI::Xaml::IApplication_Vtbl` in the current scope
```

**Comment by kennykerr** [comment]
I think this is dependent on #37, which ran into a few snags. @riverar

**Comment by riverar** [comment]
Sorry to keep you waiting, missed this issue. 

Earlier versions of the `windows-app` crate didn't emit the `implement` feature (or bring in the upstream `windows` feature). #37 does but I'll pull that out and merge it separately today. Standby.

**Comment by riverar** [comment]
@ZoeyR Give that a spin. Let me know if you run into any other issues. There's a new sample too that may be helpful.

https://github.com/microsoft/windows-app-rs/blob/8bb7a82f99327303725cf35420c233853a2f3206/crates/samples/xamlapp/src/main.rs#L38-L56
