### ISSUE TITLE
Cross compilation from Linux?

### ISSUE THREAD

**Issue by rachtsingh** [microsoft/windows-app-rs#41]
I know this project is currently experimental, and this isn't a priority, but I figured I'd document in case someone else runs into this.

I'm trying to compile the example in the README from WSL using Linux cross compilation, which includes installing MinGW:

```bash
rustup target add x86_64-pc-windows-gnu
rustup toolchain install stable-x86_64-pc-windows-gnu
sudo apt-get install mingw-w64
```

This seems to almost work (because `windows-rs` supports cross compilation, it seems) but fails when the linker tries to find the app runtime:

```
  = note: /usr/bin/x86_64-w64-mingw32-ld: cannot find -lmicrosoft.windowsappruntime.bootstrap
          collect2: error: ld returned 1 exit status
error: could not compile `rust_windows` due to previous error
```

I'm really not sure how this could be solved, but it would be nice to have the workflow in WSL more clear. Thanks!

**Comment by JasperDeSutter** [comment]
There issue is a build script needs to be run on the host system (linux), but it contains Windows specific code. It can be fixed with these changes:
* Link names should be case sensitive matches with the dll that is written from the build script ( `Microsoft.WindowsAppRuntime.Bootstrap.dll`)
* The code to be executed from a build script should not be inside the main crate which contains Windows dependencies, or the main "runtime" code should be `cfg`ed out.

See this branch with above changes that make compilation work on linux: https://github.com/JasperDeSutter/windows-app-rs/tree/linux-support

**Comment by rachtsingh** [comment]
Ok, got it to run. The above issue was solved after using the steps here: https://github.com/microsoft/WindowsAppSDK/issues/1953; in particular, I:

1. Uninstalled the v1.0.0 Windows App SDK Runtime I had installed from the link in the README
2. Downloaded version 1.0.3 (I guess v1.1.0 doesn't work) from [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads)
3. Ran the installer as administrator

And the expected app ran both in the WSL environment and in Windows, as expected.

Ideas for improving this process:

1. Please incorporate the (small) fixes in @JasperDeSutter's [branch](https://github.com/JasperDeSutter/windows-app-rs/tree/linux-support).
2. Change the README to include a link to v1.0.3 instead of v1.0.0 (which has the known bug above)
3. Include some details somewhere on the cross compilation process (maybe using my steps as a guide?), including a description of how to set up either of the MSVC or GNU targets.
4. (which I don't know anything about) include details on how the GNU toolchain finds the appropriate DLL (I guess it is part of MINGW?)

I'm happy to do any of those if you'd prefer a pull request!

**Comment by riverar** [comment]
Hey all, sorry I didn't reply sooner--lots of things moving around on my side. The README is pointing to a link that I thought was going to continue getting updates but I see I was wrong. It should be pointing to the latest 1.0.3 bits as you painfully discovered.

I'll get the crate updated right now.

**Comment by rachtsingh** [comment]
Thank you!
