### ISSUE TITLE
Error despite success

### ISSUE THREAD

**Issue by aWeinzierl** [microsoft/windows-app-rs#49]
## Problem
Functions return an error despite the function completed successfully

## Steps to reproduce

1. Combine Readme "Get started" procedure with the `xamlapp` code to create a xaml app
2. Insert into [L56](https://github.com/microsoft/windows-app-rs/blob/master/crates/samples/xamlapp/src/main.rs#L56) the following code
```Rust
dbg!(window.Content());
dbg!(Window::Current());
```
4. Compile & run the app
5. See 
```
[src\main.rs:56] window.Content() = Err(
    Error {
        code: 0x00000000,
        message: La operación se completó correctamente.
        ,
    },
)
[src\main.rs:57] Window::Current() = Err(
    Error {
        code: 0x00000000,
        message: La operación se completó correctamente.
        ,
    },
)
```

Why is an error returned instead of the desired value although there isn't an error?

## Notes
* Output from `cargo version`: cargo 1.64.0-nightly (a5e08c470 2022-06-23)
* Output from `rustup show`: 
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\andre\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc
nightly-2021-03-20-x86_64-pc-windows-msvc
nightly-2021-03-22-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27)
```
* Output from `rustup --version`: 
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27)
```
* Output from `cmd /c ver`: Microsoft Windows [Versión 10.0.19044.1766]

**Comment by riverar** [comment]
Hi @aWeinzierl,

1. `Window.Content` returns a failure HRESULT code if the window does not contain any content. If you move `dbg!(window.Content());` to after `window.SetContent(&button)?;`, you'll see it works as expected.

2. `Window::Current()` fails because it's not supported in non-UWP apps. Snippet from the docs:
   > Window.Current Property
   > For UWP apps, gets the window of the current thread. Desktop apps always return null.

   https://docs.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.window.current?view=windows-app-sdk-1.1
