### ISSUE TITLE
WinUI 3 support

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-app-rs#5]
Hi,

It's great to see that Windows App SDK is now (going to be) supported on Rust! 🙂

I would like to ask, is this the right crate to use if I want to build WinUI 3 apps using Rust?

I realize that WinUI 3 support might only be coming in the future, but I would like to ask for a clarification of the crate ecosystem.

As a somewhat related question, how does this crate relate to `windows-rs`? Does it supersede the windows-rs crate, or builds upon it?

Thanks!

**Comment by kennykerr** [comment]
Great questions!

The [windows](https://github.com/microsoft/windows-rs) crate is foundational in that it powers this new `windows-app` crate. It's early days but the `windows-app` crate is meant to make it much easier to use the [Windows App SDK](https://github.com/microsoft/WindowsAppSDK) for Rust developers. As this new set of APIs requires bootstrapping and various other hooks to get it up and running, using only the `windows` crate - while possible - is a little more cumbersome for these new APIs. 

So while the `windows` crate is still essential as it provides all of the language support, the `windows-app` crate will provide the necessary bootstrapping unique to the Windows App SDK. 

As WinUI is a large part of the Windows App SDK, the goal is to support the latest WinUI app development through the `windows-app` crate.
