### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-app-rs#6]
Do you guys have a roadmap? 🙂

Windows App SDK itself and at least WinUI 3 in particular share their roadmaps, which is very helpful for planning the adoption.

This is the opposite of the `windows-rs` crate which doesn't have a roadmap and thus it's impossible to know when, for example, full WinRT component authoring support will arrive (if ever).

Please consider sharing your roadmap! This helps a lot and also is a great way to engage with the community 🙂

**Comment by kennykerr** [comment]
The Windows App SDK and WinUI teams are quite large, spanning many talented engineers, and thus have the resources to plan and commit to an ambitious roadmap. 

On the other hand, the various Rust teams at Microsoft are quite small in comparison, making it harder to plan or predict when certain features will be available. Full component authoring support, for example, is definitely on my roadmap but I couldn't tell you with any certainty when that will be available.
