### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-app-rs#9]
While the existence of [windows-samples-rs](https://github.com/microsoft/windows-samples-rs) is fantastic, I think it would be a mistake to not include any examples in this repo. Rust devs expect to find examples in an examples folder than can be run with `cargo run --example`. It would be great balance to have a least one basic example in this repo + a README in the examples folder explaining that more can be found in windows-samples-rs.

**Comment by allan2** [comment]
I'm looking forward to the first Hello World or Counter!

**Comment by rylev** [comment]
Note that https://github.com/microsoft/windows-samples-rs/pull/4 will add Windows App SDK examples to the samples repo, but this issue is explicitly to add at least one example to this repo for discoverability purposes.

**Comment by kennykerr** [comment]
For now, I've just added a readme that points to the samples repo. When the windows-app crate is a little further along, we can reconsider whether an example might be appropriate.
